ALTER TABLE agrocarbon.produtores
ADD COLUMN rua VARCHAR(255),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN complemento VARCHAR(100),
ADD COLUMN bairro VARCHAR(100),
ADD COLUMN cidade VARCHAR(100),
ADD COLUMN estado VARCHAR(50),
ADD COLUMN cep VARCHAR(20);